/**
 * Generated-file rules — BALANCE_WEB_HANDOFF.md §6.
 * damage-config.yml = line-level patch of the original file.
 * tuning-config.yml = full regeneration diffed against hardcoded values.
 */
import type {CoiBalancePayload, DamageChange, EnrichedAbility} from '@/types/coi-balance';

const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * Patch payload.damageConfigLines in place: replace only the value part of the
 * edited keys inside their pathway section. Never add/remove/reorder lines,
 * never touch comments or `version:`. Unmatched keys are skipped silently.
 */
export function patchedDamageYaml(payload: CoiBalancePayload, changes: DamageChange[]): string {
    const lines = payload.damageConfigLines.slice();
    for (const c of changes) {
        let start = -1, end = lines.length;
        const secRe = new RegExp('^' + esc(c.pathway) + ':\\s*(#.*)?$');
        for (let i = 0; i < lines.length; i++) if (secRe.test(lines[i])) {
            start = i;
            break;
        }
        if (start < 0) continue; // never append sections
        for (let i = start + 1; i < lines.length; i++) if (/^\S/.test(lines[i])) {
            end = i;
            break;
        }
        const keyRe = new RegExp('^(\\s+' + esc(c.key) + ':\\s*).*$');
        for (let i = start + 1; i < end; i++) {
            const m = lines[i].match(keyRe);
            if (m) {
                lines[i] = m[1] + c.newVal;
                break;
            }
        }
    }
    return lines.join('\n') + '\n';
}

interface TuningEntry {
    cooldown?: number;
    cost?: number;
    'cost-percentage'?: number;
    'cooldown-categories'?: Record<string, number>;
}

/**
 * Every ability whose effective values differ from the HARDCODED ones (§6):
 * pre-existing server overrides survive regeneration because the diff is
 * against _hard, not _eff0. Precedence: flat `cost` beats `cost-percentage`.
 */
export function tuningEntries(abilities: EnrichedAbility[]): Record<string, Record<string, TuningEntry>> {
    const out: Record<string, Record<string, TuningEntry>> = {};
    for (const a of abilities) {
        const entry: TuningEntry = {};
        if (a._hard.cd >= 0 && a.effectiveCooldownSeconds !== a._hard.cd)
            entry.cooldown = a.effectiveCooldownSeconds;
        const cats: Record<string, number> = {};
        for (const cat of Object.keys(a._hard.cats))
            if (a.effectiveCategoryCooldowns[cat] !== a._hard.cats[cat])
                cats[cat] = a.effectiveCategoryCooldowns[cat];
        if (Object.keys(cats).length) entry['cooldown-categories'] = cats;
        if (a._hard.pct > 0) {
            if (a.effectiveFlatCost > 0) entry.cost = a.effectiveFlatCost; // flat override on a %-cost ability
            else if (a.effectiveCostPercentage !== a._hard.pct) entry['cost-percentage'] = a.effectiveCostPercentage;
        } else if (a.effectiveFlatCost !== a._hard.flat) {
            entry.cost = a.effectiveFlatCost;
        }
        if (Object.keys(entry).length) (out[a.pathway] = out[a.pathway] || {})[a.kebabName] = entry;
    }
    return out;
}

export function tuningYaml(abilities: EnrichedAbility[]): string {
    const entries = tuningEntries(abilities);
    const lines = [
        '# Balance tuning overrides — generated by the balance dashboard.',
        '# Drop over plugins/CircleOfImagination/tuning-config.yml and run /coi reload.',
        'version: 1.0.0',
        '',
        Object.keys(entries).length ? 'overrides:' : 'overrides: {}',
    ];
    for (const pathway of Object.keys(entries).sort()) {
        lines.push('  ' + pathway + ':');
        for (const key of Object.keys(entries[pathway]).sort()) {
            lines.push('    ' + key + ':');
            const entry = entries[pathway][key];
            for (const field of ['cooldown', 'cost', 'cost-percentage'] as const)
                if (entry[field] !== undefined) lines.push('      ' + field + ': ' + entry[field]);
            if (entry['cooldown-categories']) {
                lines.push('      cooldown-categories:');
                for (const cat of Object.keys(entry['cooldown-categories']).sort())
                    lines.push('        ' + cat + ': ' + entry['cooldown-categories'][cat]);
            }
        }
    }
    return lines.join('\n') + '\n';
}

export function downloadText(filename: string, text: string): void {
    const blob = new Blob([text], {type: 'text/yaml'});
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
}
